intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libboost-graph%lib{boost_graph}

lib{mymodule}: {hxx ixx txx cxx mxx}{** -version} mxx{version} $impl_libs $intf_libs

mxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DMYMODULE_STATIC_BUILD
objs{*}: cxx.poptions += -DMYMODULE_SHARED_BUILD

# Export options.
#
lib{mymodule}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mymodule}: cxx.export.poptions += -DMYMODULE_STATIC
libs{mymodule}: cxx.export.poptions += -DMYMODULE_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{mymodule}: bin.lib.version = "-$version.project_id"
else
  lib{mymodule}: bin.lib.version = "-$version.major.$version.minor"

# Install into the mymodule/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx mxx}{*}:
{
  install         = include/mymodule/
  install.subdirs = true
}
